config/routes.rb
Rails.application.routes.draw do
  get    '/createc', to: 'companies#new'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'houses/find'
  post 'houses/search'
  resources :users
  resources :companies
  resources :houses
  resources :inquries
  resources :pbuyers
end

app/models/inqury.rb
class Inqury < ApplicationRecord
  belongs_to :pbuyer
end

app/controllers/inquries_controller.rb
class InquriesController < ApplicationController
  before_action :set_inqury, only: [:show, :edit, :update, :destroy]

  # GET /inquries
  # GET /inquries.json
  def index
    @pid = params[:pid]
    @inquries = Inqury.where("pbuyer_id = ?", @pid).all
    #@inquries = Inqury.all
  end

  # GET /inquries/1
  # GET /inquries/1.json
  def show
    @pid = params[:pid]
  end

  # GET /inquries/new
  def new
    @pid = params[:pid]
    @inqury = Inqury.new
  end

  # GET /inquries/1/edit
  def edit
    if (!(current_user.realtor?))
      @pid = params[:pid]
    end
  end

  # POST /inquries
  # POST /inquries.json
  def create
    @pid = inqury_params[:pbuyer_id]
    @inqury = Inqury.new(inqury_params)

    respond_to do |format|
      if @inqury.save
        format.html { redirect_to inqury_path(@inqury, :pid=>@pid), notice: 'Inqury was successfully created.' }
        format.json { render :show, status: :created, location: @inqury }
      else
        format.html { render :new }
        format.json { render json: @inqury.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquries/1
  # PATCH/PUT /inquries/1.json
  def update
    if (!(current_user.realtor?))
      @pid = inqury_params[:pbuyer_id]
      respond_to do |format|
        if @inqury.update(inqury_params)
          format.html { redirect_to inqury_path(@inqury, :pid => @pid), notice: 'Inqury was successfully updated.' }
          format.json { render :show, status: :ok, location: @inqury }
        else
          format.html { render :edit }
          format.json { render json: @inqury.errors, status: :unprocessable_entity }
        end
      end
    end
    /**if (current_user.realtor?)
      @inqury = Inqury.find(params[:id])
      if @inqury.update_attributes(inqury_params)
        flash[:success] = "Profile updated"
        redirect_to @inqury
      else
        render 'edit'
      end
    end*/
  end

  # DELETE /inquries/1
  # DELETE /inquries/1.json
  def destroy
    @pid = params[:pid]
    @inqury.destroy
    respond_to do |format|
      format.html { redirect_to inquries_url(:pid => @pid), notice: 'Inqury was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inqury
      @inqury = Inqury.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inqury_params
      params.require(:inqury).permit(:subject, :content, :pbuyer_id)
    end
end

app/views/inquries/_form.html.erb
<%= form_with(model: inqury, local: true) do |form| %>
  <% if inqury.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inqury.errors.count, "error") %> prohibited this inqury from being saved:</h2>

      <ul>
      <% inqury.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <%=form.hidden_field :pbuyer_id, :value=>@pid %>

  <div class="actions">
    <%= form.submit(:pid => @pid) %>
  </div>
<% end %>

app/views/inquries/_form1.html.erb
<%=form_tag(reply_inqury_path, method: "post") do%>
  <% if inqury.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inqury.errors.count, "error") %> prohibited this inqury from being saved:</h2>

      <ul>
        <% inqury.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reply %>
    <%= form.text_field :reply %>
  </div>

  <div class="actions">
    <%= form.submit(:pid => @pid) %>
  </div>
<% end %>

app/views/inquries/edit.html.erb
<h1>Editing Inqury</h1>

<%= render 'form', inqury: @inqury, pid: @pid %>

<%= link_to 'Show', inqury_path(@inqury, :pid => @pid) %> |
<%= link_to 'Back', inquries_path(:pid => @pid) %>

app/views/inquries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inquries</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Content</th>
      <th>Reply</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquries.each do |inqury| %>
      <tr>
        <td><%= inqury.subject %></td>
        <td><%= inqury.content %></td>
        <td><%= inqury.reply %></td>
        <td><%= link_to 'Show', inqury_path(inqury, :pid => @pid) %></td>
        <td><%= link_to 'Edit', edit_inqury_path(inqury, :pid => @pid) %></td>
        <td><%= link_to 'Destroy',inqury_path(inqury, :pid=>@pid) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Inqury', new_inqury_path(:pid => @pid) %>
<%= link_to 'Back', pbuyers_path %>

app/views/inquries/new.html.erb
<h1>New Inqury</h1>

<%= render 'form', inqury: @inqury %>

<%= link_to 'Back', inquries_path(:pid => @pid) %>

app/views/inquries/reply.html.erb
<h1>Reply</h1>

<%= render 'form1', inqury: @inqury %>

<%= link_to 'Back', inquries_path(:pid => @pid) %>

app/views/inquries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject</strong>
  <%= @inqury.subject %>
</p>

<p>
  <strong>Content</strong>
  <%= @inqury.content %>
</p>

<%= link_to 'Edit', edit_inqury_path(@inqury, :pid => @pid) %> |
<%= link_to 'Back', inquries_path(:pid => @pid) %>