config/routes.rb
Rails.application.routes.draw do
  get    '/createc', to: 'companies#new'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'houses/find'
  post 'houses/search'
  resources :users
  resources :companies
  resources :houses
  resources :inquries
  resources :pbuyers
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :houses
	validates :Name,     presence: true, length: { maximum: 255 },
			     uniqueness: true
	validates :Website,  presence: true, length: { maximum: 255 },
			     uniqueness: { case_sensitive: false }
	validates :Address,  presence: true, length: { maximum: 255 }
	validates :Size,     presence: true, length: { maximum: 50 }
	validates :Founded,  presence: true, length: { maximum: 6 }
	validates :Revenue,  presence: true, length: { maximum: 50 }
	# validates for synopsis is not decided yet
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  
  def index
    @companies = Company.paginate(page: params[:page])
  end
  
  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end
  
  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "establish successfully"
      redirect_to @company
    else
      render 'new'
    end
  end
  
  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(company_params)
      flash[:success] = "Profile updated"
      redirect_to @company
    else
      render 'edit'
    end
  end
  
  def destroy
    Company.find(params[:id]).destroy
    flash[:success] = "Company deleted"
    redirect_to company_url
  end
  
  private

    def company_params
      params.require(:company).permit(:Name, :Website, :Address,
                                   :Size, :Founded, :Revenue)
    end

    # Before filters
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
	store_location
        flash[:danger] = "Please log in."
	redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<li>
  <%= link_to company.Name, company %>
  <%= company.Website %>
  <%= company.Address %>
  <%= company.Size %>
  <%= company.Founded %>
  <%= company.Revenue %>
  <%= company.Synopsis %>
  <%= link_to "delete", company, method: :delete, data: { confirm: "You sure?" } %>
</li>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <%= render 'shared/error_messages_company', object: @company %>

  <%= f.label :Name %>
  <%= f.text_field :Name, class: 'form-control' %>

  <%= f.label :Website %>
  <%= f.text_field :Website, class: 'form-control' %>

  <%= f.label :Address %>
  <%= f.text_field :Address, class: 'form-control' %>
  
  <%= f.label :Size %>
  <%= f.text_field :Size, class: 'form-control' %>
  
  <%= f.label :Founded %>
  <%= f.text_field :Founded, class: 'form-control' %>
  
  <%= f.label :Revenue %>
  <%= f.text_field :Revenue, class: 'form-control' %>
  
  <%= f.label :Synopsis %>
  <%= f.text_field :Synopsis, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/companies/edit.html.erb
<% provide(:title, 'Edit Companies') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/companies/index.html.erb
<% provide(:title, 'All Companies') %>
<h1>All Companies</h1>

<%= will_paginate %>

<table>
  <thead>
    <tr>
      <th>Name &emsp;&emsp;&emsp;</th>
      <th>Website &emsp;&emsp;&emsp;</th>
      <th>Address &emsp;&emsp;&emsp;</th>
      <th>Size &emsp;&emsp;&emsp;</th>
      <th>Founded &emsp;&emsp;&emsp;</th>
      <th>Revenue &emsp;&emsp;&emsp;</th>
      <th>Synopsis &emsp;&emsp;&emsp;</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

	<% @companies.each do |company| %>
      <tr>
        <td><%= company.Name %></td>
        <td><%= company.Website %></td>
        <td><%= company.Address %></td>
        <td><%= company.Size %></td>
        <td><%= company.Founded %></td>
        <td><%= company.Revenue %></td>
        <td><%= company.Synopsis %></td>
        <td><%= link_to 'Show', company %>&nbsp;</td>
        <td><%= link_to 'Edit', edit_company_path(company) %>&nbsp;</td>
        <td><%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;</td>
      </tr>
    <% end %>

  </tbody>
</table>	
	
<%= will_paginate %>

app/views/companies/new.html.erb
<% provide(:title, 'Create Company') %>
<% provide(:button_text, 'Create Company') %>
<h1>Create New Company</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/companies/show.html.erb
<% provide(:title, @company.Name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="company_info">
	
      <p><strong>Name:</strong><%= @company.Name %></p>
	  <p><strong>Website:</strong><%= @company.Website %></p>
	  <p><strong>Address:</strong><%= @company.Address %></p>
	  <p><strong>Size:</strong><%= @company.Size %></p>
	  <p><strong>Founded:</strong><%= @company.Founded %></p>
	  <p><strong>Revenue:</strong><%= @company.Revenue %></p>
	  <p><strong>Synopsis:</strong><%= @company.Synopsis %></p>
	  
	  <%= link_to 'Edit', edit_company_path(@company) %>
	  <%= link_to 'Back', companies_path %>	  
    </section>
  </aside>
</div>

<p><strong>Your houses:</strong>

<table>
  <thead>
    <tr>
      <th>Location &emsp;&emsp;&emsp;</th>
      <th>Square Footage &emsp;&emsp;&emsp;</th>
      <th>Year &emsp;&emsp;&emsp;</th>
      <th>Style &emsp;&emsp;&emsp;</th>
      <th>Price &emsp;&emsp;&emsp;</th>
      <th>Floors &emsp;&emsp;&emsp;</th>
      <th>Basement &emsp;&emsp;&emsp;</th>
      <th>Owner	&emsp;&emsp;&emsp;</th>
      <th>Contact &emsp;&emsp;&emsp;</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company.houses.each do |house| %>
      <tr>
        <td><%= house.location %></td>
        <td><%= house.square_footage %></td>
        <td><%= house.year %></td>
        <td><%= house.style %></td>
        <td><%= house.price %></td>
        <td><%= house.floors %></td>
        <td><%= house.basement %></td>
        <td><%= house.owner %></td>
        <td><%= house.contact %></td>
        <td><%= link_to 'Show', house %>&nbsp;</td>
        <td><%= link_to 'Edit', edit_house_path(house) %>&nbsp;</td>
        <td><%= link_to 'Delete', house, method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;</td>
      </tr>
	<% end %>
  </tbody>
</table>